
class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainingArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
#entities
